/* Generated By:JavaCC: Do not edit this line. JSONPathCompilerTreeConstants.java Version 5.0 */
package us.monoid.web.jp.javacc;

public interface JSONPathCompilerTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTARRAY = 1;
  public int JJTSELECTOR = 2;
  public int JJTTERM = 3;
  public int JJTNEG = 4;
  public int JJTPART = 5;
  public int JJTPREDICATE = 6;
  public int JJTIMAGE = 7;
  public int JJTOBJECT = 8;


  public String[] jjtNodeName = {
    "EXPRESSION",
    "ARRAY",
    "selector",
    "term",
    "neg",
    "part",
    "predicate",
    "IMAGE",
    "OBJECT",
  };
}
/* JavaCC - OriginalChecksum=b8e96437e0cbdae2a9d570aaa7031380 (do not edit this line) */
