/* Generated By:JavaCC: Do not edit this line. JSONPathCompilerTreeConstants.java Version 5.0 */
package de.monoid.web.jp.javacc;

public interface JSONPathCompilerTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTARRAY = 1;
  public int JJTSELECTOR = 2;
  public int JJTTERM = 3;
  public int JJTNEG = 4;
  public int JJTPART = 5;
  public int JJTPREDICATE = 6;
  public int JJTOBJECT = 7;


  public String[] jjtNodeName = {
    "EXPRESSION",
    "ARRAY",
    "selector",
    "term",
    "neg",
    "part",
    "predicate",
    "OBJECT",
  };
}
/* JavaCC - OriginalChecksum=c7088bf35c9f1917e594638c2f81c313 (do not edit this line) */
