/* Generated By:JJTree&JavaCC: Do not edit this line. JSONPathCompilerConstants.java */
package de.monoid.web.jp.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JSONPathCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int CNAME = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int DIGIT19 = 8;
  /** RegularExpression Id. */
  int DOT = 9;
  /** RegularExpression Id. */
  int OR = 10;
  /** RegularExpression Id. */
  int AND = 11;
  /** RegularExpression Id. */
  int NOT = 12;
  /** RegularExpression Id. */
  int OP = 13;
  /** RegularExpression Id. */
  int INTEGER = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;
  /** RegularExpression Id. */
  int FRAC = 16;
  /** RegularExpression Id. */
  int EXP = 17;
  /** RegularExpression Id. */
  int EXPONENT = 18;
  /** RegularExpression Id. */
  int IDENTIFIER = 19;
  /** RegularExpression Id. */
  int OPEN_ARRAY = 20;
  /** RegularExpression Id. */
  int CLOSE_ARRAY = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<LETTER>",
    "<CNAME>",
    "<DIGIT>",
    "<DIGIT19>",
    "\".\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "<OP>",
    "<INTEGER>",
    "<NUMBER>",
    "<FRAC>",
    "<EXP>",
    "<EXPONENT>",
    "<IDENTIFIER>",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
  };

}
